stages:
  - build
  - test

install-fedora:
  stage: build
  image: fedora:31
  script:
    - ./install.sh -an

install-arch:
  stage: build
  image: archlinux
  script:
    - echo "In progress..."

test:
  stage: test
  script:
    - ./test.sh
