stages:
  - build
  - test

install-fedora:
  stage: build
  image: fedora:31
  script:
    - ./install.sh -an
  only:
    - master

test:
  stage: test
  script:
    - ./tests.sh
  only:
    - master
