tests:
  image: fedora:31
  before_script:
    - dnf install --assumeyes zsh which "dnf-command(copr)" python3-pip
    - export PATH=$PATH:$HOME/.local/bin
  script:
    - ./install.sh --all
    - which git
    - which alacritty
    - which tmux
    - which nvim
    - which fzf
    - which exa
    - which bat
    - which fd
    - which jq
    - which rg
    - which pipx
    - which black
    - which docformatter
    - which ipython
    - which poetry
    - ls $HOME/.cargo/bin/cargo
    - ls $HOME/.config
    - ls $HOME/.local/share
    - ls $HOME/.local/bin
    - ls $HOME/.oh_my_zsh
    - ls $HOME/.oh_my_zsh/custom/themes/powerlevel10k
    - ls $HOME/.oh_my_zsh/custom/plugins/fast-syntax-highlighting
    - ls $HOME/.oh_my_zsh/custom/plugins/zsh-autosuggestions
    - ls $HOME/.tmux.conf
    - ls $HOME/.tmux/plugins/tpm
    - ls $HOME/.dir_colors
    - ls $HOME/.local/bin/diff-so-fancy
    - ls $HOME/.zshrc
    - ls $HOME/.config/nvim/init.vim
    - ls $HOME/.config/alacritty/alacritty.yml
    - ls $HOME/.config/flake8
    - ls $HOME/.virtualenv
    - ls $HOME/.config/flake8-black/pyproject.toml
    - ls $HOME/.isort.cfg
