tests:
  image: fedora:31
  before_script:
    - dnf install --assumeyes "dnf-command(copr)" python3-pip
    - export PATH=$PATH:$HOME/.local/bin
  script:
    - ./install.sh --all --no-updates
    - command -v git
    - command -v alacritty
    - command -v tmux
    - command -v nvim
    - command -v fzf
    - command -v exa
    - command -v bat
    - command -v fd
    - command -v jq
    - command -v rg
    - command -v pipx
    - command -v black
    - command -v docformatter
    - command -v ipython
    - command -v poetry
    - command -v i3
    - command -v rofi
    - command -v feh
    - command -v redshift
    - ls $HOME/.cargo/bin/cargo
    - ls $HOME/.config
    - ls $HOME/.local/share
    - ls $HOME/.local/bin
    - ls $HOME/.antigen
    - ls $HOME/.tmux.conf
    - ls $HOME/.tmux/plugins/tpm
    - ls $HOME/.local/share/nord_dir_colors
    - ls $HOME/.local/share/nvim/site/autoload/plug.vim
    - ls $HOME/.tmux/plugins/tpm
    - ls $HOME/.local/bin/diff-so-fancy
    - ls $HOME/.zshrc
    - ls $HOME/.config/nvim/init.vim
    - ls $HOME/.config/alacritty/alacritty.yml
    - ls $HOME/.config/flake8
    - ls $HOME/.virtualenv
    - ls $HOME/.config/flake8-black/pyproject.toml
    - ls $HOME/.isort.cfg
    - ls $HOME/.config/i3/config
    - ls $HOME/.config/rofi/config.rasi
