preload = ~/.config/dotfiles/wallpaper/wallpaper.png
preload = ~/.config/dotfiles/wallpaper/wallpaper-vertical.png

wallpaper = DP-2,~/.config/dotfiles/wallpaper/wallpaper.png
wallpaper = DP-3,~/.config/dotfiles/wallpaper/wallpaper-vertical.png
