[tool.flakehell]
max_line_length = 120
show_source = true

[tool.flakehell.plugins]
flake8-black = ["+*"]
flake8-breakpoint = ["+*"]
flake8-bugbear = ["+*"]
flake8-comprehensions = ["+*"]
flake8-django = ["+*"]
mccabe = ["+*"]
pycodestyle = ["+*"]
pyflakes = ["+*"]
pylint = ["+*"]
