#!/usr/bin/env bash

set -euo pipefail

main() {
	is-in-git-repo || return
	git restore "$(
		git ls-files --modified |
			fzf \
				--multi \
				--border-label "Select a file" \
				--preview 'git diff {+1} | delta'
	)"
}

main "$@"
