#!/usr/bin/env bash

set -euo pipefail

main() {
	is-in-git-repo || (echo "Not in a git repo" && exit 1)
	# shellcheck disable=SC2046
	git restore $(
		git ls-files --modified |
			fzf \
				--multi \
				--exit-0 \
				--border-label "Select a file" \
				--preview 'git diff {+1} | delta' |
			paste -d' ' -s -
	)
}

main "$@"
