#!/usr/bin/env bash

set -euo pipefail

main () {
    is-in-git-repo || return
    git restore $(
        git ls-files --modified |
            fzf \
                --header "Select a file" \
                -m \
                --preview 'git diff {+1} | delta'
    )
}

main "$@"
