#!/usr/bin/env bash

# source: https://github.com/junegunn/fzf/wiki/Examples#tmux
# tm - create new tmux session, or switch to existing one. Works from within tmux too. (@bag-man)
# `tm` will allow you to select your tmux session via fzf.
# `tm irc` will attach to the irc session (if it exists), else it will create it.

main() {
	source "$HOME/.zshenv"
	local session=$1
	[[ -n $TMUX ]] && change="switch-client" || change="attach-session"
	if [ "$session" ]; then
		tmux "$change" -t "$1" 2>/dev/null ||
			(tmux new-session -d -s "$1" &&
				tmux "$change" -t "$1")
		return
	fi

	# otherwise, use the usual fzf script to attach to one or complaint there's no sessions
	session=$(
		tmux list-sessions -F "#{session_name}" 2>/dev/null |
			fzf --select-1 --exit-0 \
				--preview 'tmux list-windows -t {}' \
				--preview-label 'Llista de finestres' \
				--border-label 'Sel·lecciona una sessió'
	) &&
		tmux "$change" -t "$session" || echo "No sessions found."
	unset session
}

main "$@"
