#!/usr/bin/env bash


function vt() {
    local FILENAME
    FILENAME=${1:-"t.py"}

    if test -f $FILENAME; then
        echo "File '$FILENAME' already exists."
        exit 1
    fi

    cp -p $DOTFILES/templates/t.py "$FILENAME"
    "$EDITOR" "$FILENAME"
}

vt "$@"
