---
views:
  v1/pods:
    sortColumn: NAME:desc
    columns:
      - NAME
      - PF
      - READY
      - RESTARTS
      - STATUS
      - CPU
      - "%CPU/R"
      - MEM
      - "%MEM/R"
      - IP
      - NODE
      - AGE
