# starship config

add_newline = false
format = """\
    $username\
    $hostname\
    $directory\
    $python\
    $git_branch\
    $git_status\
    $git_state\
    $jobs\
    $character
"""

[username]
    show_always = false
    style_user = "cyan"
    format = "[$user]($style) "

[hostname]
    ssh_only = true
    style = "purple"
    format =" [$hostname]($style) "

[directory]
    style = "bold #81a1c1"
    truncate_length = 3
    truncate_to_rep0o = true
    read_only = " "
    format = "[$path]($style)[$read_only]($read_only_style) "

[python]
    format = '[${version} (\($virtualenv\) )]($style)'
    style = "green bold"


[git_branch]
    style = "bold #5e81ac"
    format = "[$symbol$branch]($style) "

[git_status]
    style = "bold #d08770"
    show_sync_count = true
    ahead = "⇡${count}"
    diverged = "⇡${ahead_count}/⇣${behind_count}"
    behind = "⇣${count}"

[git_state]
    format = "[($state( $progress_current of $progress_total ))]($style) "

[character]
    success_symbol = "[➜](bold #d8dee9)"
    error_symbol = "[✗](bold red)"
