# starship config

add_newline = false
prompt_order = [
    "username",
    "hostname",
    "directory",
    "custom.virtualenv",
    "git_branch",
    "git_status",
    "git_state",
    "jobs",
    "character"
]

[username]
    show_always = false

[hostname]
    ssh_only = true
    prefix = ""
    suffix = ""

[directory]
    truncate_length = 3
    truncate_to_rep0o = true
    prefix = "in "

[custom.virtualenv]
    command = "python3 -c \"import os; print(os.getenv('VIRTUAL_ENV').split('/').pop())\""
    when = "test $VIRTUAL_ENV"
    prefix = "("
    suffix = ") "

[git_status]
    show_sync_count = true

[git_state]
    rebase = "REBASING"
    merge = "MERGING"
    revert = "REVERTING"
    cherry_pick = "CHERRY-PICKING"
    bisect = "BISECTING"
    progress_divider = " of "

[git_branch]
    symbol = ""

[character]
    symbol = "➜"
    error_symbol = "✗"
    use_symbol_for_status = true
