# starship config

add_newline = false
format = """\
    $username\
    $hostname\
    $directory\
    $env_var\
    $git_branch\
    $git_status\
    $git_state\
    $jobs\
    $character
"""

[username]
    show_always = false

[hostname]
    ssh_only = true
    format ="on [$hostname] "

[directory]
    truncate_length = 3
    truncate_to_rep0o = true
    read_only = " "
    format = "[$path]($style)[$read_only]($read_only_style) "

[env_var]
    variable = "VIRTUAL_ENV"
    style = "yellow bold"
    format = '[\($env_value\)]($style) '

[git_status]
    show_sync_count = true
    ahead = "⇡${count}"
    diverged = "⇡${ahead_count}/⇣${behind_count}"
    behind = "⇣${count}"

[git_state]
    format = "[($state( $progress_current of $progress_total ))]($style) "

[character]
    success_symbol = "[➜](bold green)"
    error_symbol = "[✗](bold red)"
